import type { NextPage } from 'next'
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [guess, setGuess] = useState("");
  const [palpitesFeitos, setPalpitesFeitos] = useState<string[]>([]);

  let randomNumber = Math.floor(Math.random() * 100);

  let guessCount = 1;

  const handleCheckGuess = (e: any) => {
    e.preventDefault();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Guess Number</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Guess Number</h1>

        <div>
          <p>
            Selecionamos um número aleatório entre 1 e 100. Veja se consegue
            adivinhar em 10 chances ou menos. Nós lhe diremos se seu palpite
            está com valor alto ou baixo.
          </p>
        </div>

        <form onSubmit={handleCheckGuess}>
          <input
            placeholder="Digite o número que você está imaginando"
            aria-label="Digite o número que você está imaginando"
            value={guess}
            onChange={(e) => setGuess(e.target.value)}
          />
          <button type="submit">Enviar Palpite</button>
        </form>
      </main>
    </div>
  );
};

export default Home
